name: Build Manager

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'apd/**'
      - 'build.gradle.kts'
      - 'gradle/libs.versions.toml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'apd/**'
      - 'build.gradle.kts'
      - 'gradle/libs.versions.toml'
  workflow_dispatch:

jobs:
  build-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: parse_version
        run: |
          COMMIT_NUM=$(git rev-list --count HEAD)
          VERSION=$(echo "$COMMIT_NUM + 200 + 10000" | bc)
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v6
        with:
          version: 1.12.1

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - name: Install toolchain
        run: |
          rustup default stable
          rustup update stable
          cargo install cargo-ndk
          rustup target install aarch64-linux-android

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: apd
          cache-targets: false

      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          ./gradlew clean assembleRelease

      - name: Debug APK Output
        run: |
          echo "Listing APK output directory:"
          ls -R app/build/outputs/apk/

      - name: Rename APK with Date
        id: rename_apk
        run: |
          DATE=$(date +%Y%m%d)
          VERSION=${{ steps.parse_version.outputs.VERSION }}
          COMMIT_SHA=$(git rev-parse --short HEAD)
          ORIGINAL_APK=$(ls app/build/outputs/apk/release/*.apk | head -n 1)
          NEW_APK_NAME="APatch_${VERSION}_${COMMIT_SHA}_${DATE}-release.apk"
          mv "$ORIGINAL_APK" "app/build/outputs/apk/release/$NEW_APK_NAME"
          echo "Renamed APK to: $NEW_APK_NAME"
          echo "APK_NAME=$NEW_APK_NAME" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: APatch
          path: app/build/outputs/apk/release/${{ steps.rename_apk.outputs.APK_NAME }}

      - name: Create Release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          name: Release ${{ steps.parse_version.outputs.VERSION }}
          artifacts: app/build/outputs/apk/release/${{ steps.rename_apk.outputs.APK_NAME }}
          generateReleaseNotes: true
          makeLatest: true
          replacesArtifacts: true
